name: go-coverage
on:
  push:
    branches:
      - main
    
jobs:
  coverage:
    name: cov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
